import { describe, it, expect } from 'vitest';
import { formatSqlValue, buildInsertSql, parseEnumValues, buildDefaultTableQuery, buildCreateTableSql, buildAlterTableSql, type CreateTableColumn, type AlterTableColumn } from './sql';

describe('parseEnumValues', () => {
  it('parses a standard enum type', () => {
    expect(parseEnumValues("enum('active','inactive','pending')")).toEqual(['active', 'inactive', 'pending']);
  });

  it('parses a single-value enum', () => {
    expect(parseEnumValues("enum('only')")).toEqual(['only']);
  });

  it('unescapes single quotes inside values', () => {
    expect(parseEnumValues("enum('O\\'Brien','Smith')")).toEqual(["O'Brien", 'Smith']);
  });

  it('unescapes backslashes inside values', () => {
    expect(parseEnumValues("enum('C:\\\\path')")).toEqual(['C:\\path']);
  });

  it('returns null for non-enum types', () => {
    expect(parseEnumValues('varchar(100)')).toBeNull();
    expect(parseEnumValues('int')).toBeNull();
  });

  it('returns null for an empty string', () => {
    expect(parseEnumValues('')).toBeNull();
  });

  it('is case-insensitive for the ENUM keyword', () => {
    expect(parseEnumValues("ENUM('a','b')")).toEqual(['a', 'b']);
  });
});

describe('formatSqlValue', () => {
  it('renders NULL for null', () => {
    expect(formatSqlValue(null)).toBe('NULL');
  });

  it('wraps strings in single quotes', () => {
    expect(formatSqlValue('Alice')).toBe("'Alice'");
  });

  it('escapes embedded single quotes', () => {
    expect(formatSqlValue("O'Brien")).toBe("'O\\'Brien'");
  });

  it('escapes embedded backslashes', () => {
    expect(formatSqlValue('C:\\Users')).toBe("'C:\\\\Users'");
  });

  it('escapes backslash before single quote', () => {
    expect(formatSqlValue("it\\'s")).toBe("'it\\\\\\'s'");
  });

  it('passes integers through unquoted', () => {
    expect(formatSqlValue(42)).toBe('42');
  });

  it('passes floats through unquoted', () => {
    expect(formatSqlValue(3.14)).toBe('3.14');
  });

  it('handles empty string', () => {
    expect(formatSqlValue('')).toBe("''");
  });

  it('renders true/false for booleans', () => {
    expect(formatSqlValue(true)).toBe('true');
    expect(formatSqlValue(false)).toBe('false');
  });
});

describe('buildInsertSql', () => {
  it('produces a valid single-row INSERT', () => {
    expect(buildInsertSql('users', { name: 'Eve', age: 28, email: null })).toBe(
      "INSERT INTO `users`\n  (`name`, `age`, `email`)\nVALUES\n  ('Eve', 28, NULL);"
    );
  });

  it('handles no columns (edge case)', () => {
    expect(buildInsertSql('users', {})).toBe('INSERT INTO `users` () VALUES ();');
  });

  it('backtick-escapes column names', () => {
    const sql = buildInsertSql('t', { col: 'v' });
    expect(sql).toContain('`col`');
  });

  it('backtick-escapes table name', () => {
    const sql = buildInsertSql('my table', { col: 1 });
    expect(sql).toContain('`my table`');
  });
});

describe('buildDefaultTableQuery', () => {
  it('returns the unsorted template when there is no auto-inc PK', () => {
    expect(buildDefaultTableQuery('users', null)).toBe('SELECT *\nFROM `users`\nLIMIT 100;');
  });

  it('appends ORDER BY <pk> DESC when an auto-inc PK is provided', () => {
    expect(buildDefaultTableQuery('orders', 'id')).toBe(
      'SELECT *\nFROM `orders`\nORDER BY `id` DESC\nLIMIT 100;',
    );
  });

  it('backtick-escapes both the table name and the PK column', () => {
    const sql = buildDefaultTableQuery('my table', 'order id');
    expect(sql).toContain('`my table`');
    expect(sql).toContain('`order id`');
  });
});

describe('buildCreateTableSql', () => {
  const idCol: CreateTableColumn = {
    name: 'id', type: 'INT', nullable: false, default: null, autoIncrement: true, pk: true,
  };
  const nameCol: CreateTableColumn = {
    name: 'name', type: 'VARCHAR(255)', nullable: false, default: null, autoIncrement: false, pk: false,
  };

  it('emits AUTO_INCREMENT and backtick quoting for MySQL', () => {
    const sql = buildCreateTableSql('mysql', null, 'users', [idCol, nameCol]);
    expect(sql).toBe(
      'CREATE TABLE `users` (\n' +
      '  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n' +
      '  `name` VARCHAR(255) NOT NULL\n' +
      ');',
    );
  });

  it('emits IDENTITY clause and double-quote quoting for Postgres', () => {
    const sql = buildCreateTableSql('postgres', null, 'users', [idCol, nameCol]);
    expect(sql).toBe(
      'CREATE TABLE "users" (\n' +
      '  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n' +
      '  "name" VARCHAR(255) NOT NULL\n' +
      ');',
    );
  });

  it('qualifies the table with the schema when one is provided', () => {
    const sql = buildCreateTableSql('mysql', 'shop', 'users', [idCol]);
    expect(sql).toContain('CREATE TABLE `shop`.`users` (');
  });

  it('omits NOT NULL when the column is nullable, no PK, and not auto-inc', () => {
    const col: CreateTableColumn = {
      name: 'note', type: 'TEXT', nullable: true, default: null, autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).not.toContain('NOT NULL');
  });

  it('forces NOT NULL on PK columns even when nullable is set', () => {
    // PK columns are implicitly NOT NULL — keep the DDL valid regardless of UI state.
    const col: CreateTableColumn = {
      name: 'id', type: 'INT', nullable: true, default: null, autoIncrement: false, pk: true,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).toContain('`id` INT NOT NULL PRIMARY KEY');
  });

  it('forces NOT NULL on auto-inc / IDENTITY columns', () => {
    const col: CreateTableColumn = {
      name: 'id', type: 'BIGINT', nullable: true, default: null, autoIncrement: true, pk: false,
    };
    const sql = buildCreateTableSql('postgres', null, 't', [col]);
    expect(sql).toContain('"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY');
  });

  it('passes DEFAULT through verbatim — caller is responsible for quoting', () => {
    const lit: CreateTableColumn = {
      name: 's', type: 'VARCHAR(10)', nullable: true, default: "'hi'", autoIncrement: false, pk: false,
    };
    const fn: CreateTableColumn = {
      name: 'created_at', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP', autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [lit, fn]);
    expect(sql).toContain("`s` VARCHAR(10) DEFAULT 'hi'");
    expect(sql).toContain('`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP');
  });

  it('skips DEFAULT when the value is null or empty', () => {
    const col: CreateTableColumn = {
      name: 'x', type: 'INT', nullable: true, default: '', autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).not.toContain('DEFAULT');
  });

  it('strips embedded quote characters from identifiers to keep DDL safe', () => {
    // No "smart escaping" here — we just remove the offending character so
    // the user can't accidentally close the quoted identifier mid-token.
    const sql = buildCreateTableSql('mysql', null, 'evil`name', [idCol]);
    expect(sql).toContain('CREATE TABLE `evilname` (');
  });
});

describe('buildAlterTableSql', () => {
  const base: CreateTableColumn = {
    name: 'email', type: 'VARCHAR(255)', nullable: false, default: null, autoIncrement: false, pk: false,
  };

  function col(overrides: Partial<AlterTableColumn> & { originalName: string | null }): AlterTableColumn {
    return {
      name: overrides.originalName ?? 'col',
      type: 'INT',
      nullable: true,
      default: null,
      autoIncrement: false,
      pk: false,
      dropped: false,
      ...overrides,
    };
  }

  it('returns empty array when nothing changed', () => {
    const cur: AlterTableColumn[] = [{ ...base, originalName: 'email', dropped: false }];
    expect(buildAlterTableSql('mysql', null, 't', cur, [base])).toEqual([]);
  });

  it('MySQL: ADD COLUMN', () => {
    const newCol = col({ originalName: null, name: 'age', type: 'INT', nullable: true });
    const stmts = buildAlterTableSql('mysql', null, 'users', [newCol], []);
    expect(stmts).toHaveLength(1);
    expect(stmts[0]).toContain('ADD COLUMN `age` INT');
  });

  it('MySQL: DROP COLUMN', () => {
    const dropped = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: false, dropped: true });
    const stmts = buildAlterTableSql('mysql', null, 'users', [dropped], [base]);
    expect(stmts).toHaveLength(1);
    expect(stmts[0]).toContain('DROP COLUMN `email`');
  });

  it('MySQL: CHANGE COLUMN on rename', () => {
    const renamed = col({ originalName: 'email', name: 'mail', type: 'VARCHAR(255)', nullable: false });
    const stmts = buildAlterTableSql('mysql', null, 'users', [renamed], [base]);
    expect(stmts).toHaveLength(1);
    expect(stmts[0]).toContain('CHANGE COLUMN `email` `mail` VARCHAR(255) NOT NULL');
  });

  it('MySQL: CHANGE COLUMN on type change', () => {
    const modified = col({ originalName: 'email', name: 'email', type: 'TEXT', nullable: false });
    const stmts = buildAlterTableSql('mysql', null, 'users', [modified], [base]);
    expect(stmts[0]).toContain('CHANGE COLUMN `email` `email` TEXT NOT NULL');
  });

  it('MySQL: combines multiple clauses in one ALTER TABLE', () => {
    const dropped = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: false, dropped: true });
    const added = col({ originalName: null, name: 'phone', type: 'VARCHAR(20)', nullable: true });
    const stmts = buildAlterTableSql('mysql', null, 'users', [dropped, added], [base]);
    expect(stmts).toHaveLength(1);
    expect(stmts[0]).toContain('DROP COLUMN');
    expect(stmts[0]).toContain('ADD COLUMN');
  });

  it('MySQL: qualifies table with schema', () => {
    const modified = col({ originalName: 'email', name: 'mail', type: 'VARCHAR(255)', nullable: false });
    const stmts = buildAlterTableSql('mysql', 'mydb', 'users', [modified], [base]);
    expect(stmts[0]).toContain('ALTER TABLE `mydb`.`users`');
  });

  it('Postgres: ADD COLUMN uses double-quote identifiers', () => {
    const added = col({ originalName: null, name: 'score', type: 'INTEGER', nullable: true });
    const stmts = buildAlterTableSql('postgres', null, 'users', [added], []);
    expect(stmts[0]).toContain('ADD COLUMN "score" INTEGER');
  });

  it('Postgres: RENAME COLUMN is a separate statement', () => {
    const pgBase: CreateTableColumn = { ...base };
    const renamed = col({ originalName: 'email', name: 'mail', type: 'VARCHAR(255)', nullable: false });
    const stmts = buildAlterTableSql('postgres', null, 'users', [renamed], [pgBase]);
    expect(stmts).toHaveLength(1);
    expect(stmts[0]).toMatch(/RENAME COLUMN "email" TO "mail"/);
  });

  it('Postgres: rename + type change produces two statements', () => {
    const pgBase: CreateTableColumn = { ...base };
    const col2 = col({ originalName: 'email', name: 'mail', type: 'TEXT', nullable: false });
    const stmts = buildAlterTableSql('postgres', null, 'users', [col2], [pgBase]);
    expect(stmts).toHaveLength(2);
    expect(stmts[0]).toContain('RENAME COLUMN');
    expect(stmts[1]).toContain('ALTER COLUMN "mail" TYPE TEXT');
  });

  it('Postgres: nullable change emits SET NOT NULL / DROP NOT NULL', () => {
    const pgBase: CreateTableColumn = { ...base, nullable: true };
    const notNull = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: false });
    const nullable = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: true });

    const stmts1 = buildAlterTableSql('postgres', null, 't', [notNull], [pgBase]);
    expect(stmts1[0]).toContain('SET NOT NULL');

    const pgBase2: CreateTableColumn = { ...base, nullable: false };
    const stmts2 = buildAlterTableSql('postgres', null, 't', [nullable], [pgBase2]);
    expect(stmts2[0]).toContain('DROP NOT NULL');
  });

  it('Postgres: default change emits SET DEFAULT / DROP DEFAULT', () => {
    const pgBase: CreateTableColumn = { ...base, default: null };
    const withDefault = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: false, default: "'anon'" });
    const stmts = buildAlterTableSql('postgres', null, 't', [withDefault], [pgBase]);
    expect(stmts[0]).toContain("SET DEFAULT 'anon'");

    const pgBase2: CreateTableColumn = { ...base, default: "'anon'" };
    const noDefault = col({ originalName: 'email', name: 'email', type: 'VARCHAR(255)', nullable: false, default: null });
    const stmts2 = buildAlterTableSql('postgres', null, 't', [noDefault], [pgBase2]);
    expect(stmts2[0]).toContain('DROP DEFAULT');
  });
});
