type CellValue = string | number | boolean | null;

export function parseEnumValues(type: string): string[] | null {
  const match = type.match(/^enum\((.+)\)$/i);
  if (!match) return null;
  const values: string[] = [];
  const re = /'((?:[^'\\]|\\.)*)'/g;
  let m;
  while ((m = re.exec(match[1])) !== null) {
    values.push(m[1].replace(/\\'/g, "'").replace(/\\\\/g, '\\'));
  }
  return values.length > 0 ? values : null;
}

export function formatSqlValue(v: CellValue): string {
  if (v === null) return 'NULL';
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  return String(v);
}

export type SqlDialect = 'mysql' | 'postgres';

export interface CreateTableColumn {
  name: string;
  /** Verbatim type token, e.g. "INT", "VARCHAR(255)", "TIMESTAMP". */
  type: string;
  nullable: boolean;
  /** Verbatim default expression — caller is responsible for quoting strings,
   *  passing CURRENT_TIMESTAMP unquoted, etc. Empty/null means no default. */
  default: string | null;
  autoIncrement: boolean;
  pk: boolean;
}

function quoteIdent(d: SqlDialect, s: string): string {
  const ch = d === 'mysql' ? '`' : '"';
  return ch + s.split(ch).join('') + ch;
}

export interface AlterTableColumn {
  /** null = new column not yet in the database. */
  originalName: string | null;
  name: string;
  type: string;
  nullable: boolean;
  default: string | null;
  autoIncrement: boolean;
  pk: boolean;
  dropped: boolean;
}

function colDefExpr(dialect: SqlDialect, col: Pick<CreateTableColumn, 'name' | 'type' | 'nullable' | 'default' | 'autoIncrement' | 'pk'>): string {
  const autoInc = dialect === 'mysql' ? 'AUTO_INCREMENT' : 'GENERATED BY DEFAULT AS IDENTITY';
  const parts: string[] = [quoteIdent(dialect, col.name), col.type];
  if (!col.nullable || col.pk || col.autoIncrement) parts.push('NOT NULL');
  if (col.default !== null && col.default !== '') parts.push(`DEFAULT ${col.default}`);
  if (col.autoIncrement) parts.push(autoInc);
  if (col.pk) parts.push('PRIMARY KEY');
  return parts.join(' ');
}

/**
 * Generate ALTER TABLE statement(s) for the given diff between the current
 * (edited) column list and the original DB baseline. Returns an array — MySQL
 * combines all clauses into one ALTER TABLE; Postgres emits RENAME COLUMN as
 * separate statements then one ALTER TABLE for the remaining changes (type,
 * nullability, default).
 */
export function buildAlterTableSql(
  dialect: SqlDialect,
  schema: string | null,
  table: string,
  current: AlterTableColumn[],
  original: CreateTableColumn[],
): string[] {
  const q = (s: string) => quoteIdent(dialect, s);
  const qualified = schema ? `${q(schema)}.${q(table)}` : q(table);
  const origMap = new Map(original.map(c => [c.name, c]));
  const stmts: string[] = [];

  if (dialect === 'mysql') {
    const clauses: string[] = [];
    for (const col of current) {
      if (col.originalName === null) {
        if (!col.dropped) clauses.push(`ADD COLUMN ${colDefExpr(dialect, col)}`);
      } else if (col.dropped) {
        clauses.push(`DROP COLUMN ${q(col.originalName)}`);
      } else {
        const orig = origMap.get(col.originalName);
        const renamed = col.name !== col.originalName;
        const changed = orig && (
          col.type !== orig.type ||
          col.nullable !== orig.nullable ||
          (col.default ?? '') !== (orig.default ?? '')
        );
        if (renamed || changed) {
          // Omit PRIMARY KEY from CHANGE COLUMN — repeating the inline constraint
          // is treated as adding a second PK and MySQL rejects it (ERROR 1068).
          clauses.push(`CHANGE COLUMN ${q(col.originalName)} ${colDefExpr(dialect, { ...col, pk: false })}`);
        }
      }
    }
    if (clauses.length > 0) {
      stmts.push(`ALTER TABLE ${qualified}\n  ${clauses.join(',\n  ')};`);
    }
  } else {
    const renames: string[] = [];
    const clauses: string[] = [];
    for (const col of current) {
      if (col.originalName === null) {
        if (!col.dropped) clauses.push(`ADD COLUMN ${colDefExpr(dialect, col)}`);
      } else if (col.dropped) {
        clauses.push(`DROP COLUMN ${q(col.originalName)}`);
      } else {
        if (col.name !== col.originalName) {
          renames.push(`ALTER TABLE ${qualified} RENAME COLUMN ${q(col.originalName)} TO ${q(col.name)};`);
        }
        const orig = origMap.get(col.originalName);
        if (orig) {
          const eff = q(col.name);
          if (col.type !== orig.type) clauses.push(`ALTER COLUMN ${eff} TYPE ${col.type}`);
          if (col.nullable !== orig.nullable) {
            clauses.push(col.nullable
              ? `ALTER COLUMN ${eff} DROP NOT NULL`
              : `ALTER COLUMN ${eff} SET NOT NULL`);
          }
          if ((col.default ?? '') !== (orig.default ?? '')) {
            if (!col.default) clauses.push(`ALTER COLUMN ${eff} DROP DEFAULT`);
            else clauses.push(`ALTER COLUMN ${eff} SET DEFAULT ${col.default}`);
          }
        }
      }
    }
    stmts.push(...renames);
    if (clauses.length > 0) {
      stmts.push(`ALTER TABLE ${qualified}\n  ${clauses.join(',\n  ')};`);
    }
  }

  return stmts;
}

/**
 * Build a CREATE TABLE statement for the given dialect. v1 supports a single
 * inline-PK column, NOT NULL / DEFAULT / AUTO_INCREMENT (or IDENTITY on pg).
 * Composite PKs, secondary indexes, FKs, and CHECK constraints are out of
 * scope; users wanting those can hand-edit the preview.
 */
export function buildCreateTableSql(
  dialect: SqlDialect,
  schema: string | null,
  table: string,
  columns: CreateTableColumn[],
): string {
  const qualified = schema
    ? `${quoteIdent(dialect, schema)}.${quoteIdent(dialect, table)}`
    : quoteIdent(dialect, table);

  const autoInc = dialect === 'mysql' ? 'AUTO_INCREMENT' : 'GENERATED BY DEFAULT AS IDENTITY';

  const lines = columns.map(c => {
    const parts: string[] = [quoteIdent(dialect, c.name), c.type];
    // PK columns are implicitly NOT NULL across both dialects; Postgres IDENTITY
    // additionally requires it. Force the constraint on so the DDL stays valid
    // even if the user ticks PK or auto-inc without un-ticking nullable.
    if (!c.nullable || c.pk || c.autoIncrement) parts.push('NOT NULL');
    if (c.default !== null && c.default !== '') parts.push(`DEFAULT ${c.default}`);
    if (c.autoIncrement) parts.push(autoInc);
    if (c.pk) parts.push('PRIMARY KEY');
    return '  ' + parts.join(' ');
  });

  return `CREATE TABLE ${qualified} (\n${lines.join(',\n')}\n);`;
}

/**
 * Default query template used when the user clicks a table in the sidebar.
 * Sorts by `pkColumn DESC` when provided so the most recent rows appear first
 * — caller passes null for tables without a single auto-incrementing PK,
 * since descending order is meaningless on UUID/string/composite keys.
 */
export function buildDefaultTableQuery(table: string, pkColumn: string | null): string {
  const orderBy = pkColumn ? `\nORDER BY \`${pkColumn}\` DESC` : '';
  return `SELECT *\nFROM \`${table}\`${orderBy}\nLIMIT 100;`;
}

export function buildInsertSql(table: string, values: Record<string, CellValue>): string {
  const cols = Object.keys(values);
  if (cols.length === 0) return `INSERT INTO \`${table}\` () VALUES ();`;
  const colList = cols.map(c => `\`${c}\``).join(', ');
  const valList = cols.map(c => formatSqlValue(values[c]!)).join(', ');
  return `INSERT INTO \`${table}\`\n  (${colList})\nVALUES\n  (${valList});`;
}
