import { describe, it, expect } from 'vitest';
import { formatSqlValue, buildInsertSql, parseEnumValues, buildDefaultTableQuery, buildCreateTableSql, type CreateTableColumn } from './sql';

describe('parseEnumValues', () => {
  it('parses a standard enum type', () => {
    expect(parseEnumValues("enum('active','inactive','pending')")).toEqual(['active', 'inactive', 'pending']);
  });

  it('parses a single-value enum', () => {
    expect(parseEnumValues("enum('only')")).toEqual(['only']);
  });

  it('unescapes single quotes inside values', () => {
    expect(parseEnumValues("enum('O\\'Brien','Smith')")).toEqual(["O'Brien", 'Smith']);
  });

  it('unescapes backslashes inside values', () => {
    expect(parseEnumValues("enum('C:\\\\path')")).toEqual(['C:\\path']);
  });

  it('returns null for non-enum types', () => {
    expect(parseEnumValues('varchar(100)')).toBeNull();
    expect(parseEnumValues('int')).toBeNull();
  });

  it('returns null for an empty string', () => {
    expect(parseEnumValues('')).toBeNull();
  });

  it('is case-insensitive for the ENUM keyword', () => {
    expect(parseEnumValues("ENUM('a','b')")).toEqual(['a', 'b']);
  });
});

describe('formatSqlValue', () => {
  it('renders NULL for null', () => {
    expect(formatSqlValue(null)).toBe('NULL');
  });

  it('wraps strings in single quotes', () => {
    expect(formatSqlValue('Alice')).toBe("'Alice'");
  });

  it('escapes embedded single quotes', () => {
    expect(formatSqlValue("O'Brien")).toBe("'O\\'Brien'");
  });

  it('escapes embedded backslashes', () => {
    expect(formatSqlValue('C:\\Users')).toBe("'C:\\\\Users'");
  });

  it('escapes backslash before single quote', () => {
    expect(formatSqlValue("it\\'s")).toBe("'it\\\\\\'s'");
  });

  it('passes integers through unquoted', () => {
    expect(formatSqlValue(42)).toBe('42');
  });

  it('passes floats through unquoted', () => {
    expect(formatSqlValue(3.14)).toBe('3.14');
  });

  it('handles empty string', () => {
    expect(formatSqlValue('')).toBe("''");
  });

  it('renders true/false for booleans', () => {
    expect(formatSqlValue(true)).toBe('true');
    expect(formatSqlValue(false)).toBe('false');
  });
});

describe('buildInsertSql', () => {
  it('produces a valid single-row INSERT', () => {
    expect(buildInsertSql('users', { name: 'Eve', age: 28, email: null })).toBe(
      "INSERT INTO `users`\n  (`name`, `age`, `email`)\nVALUES\n  ('Eve', 28, NULL);"
    );
  });

  it('handles no columns (edge case)', () => {
    expect(buildInsertSql('users', {})).toBe('INSERT INTO `users` () VALUES ();');
  });

  it('backtick-escapes column names', () => {
    const sql = buildInsertSql('t', { col: 'v' });
    expect(sql).toContain('`col`');
  });

  it('backtick-escapes table name', () => {
    const sql = buildInsertSql('my table', { col: 1 });
    expect(sql).toContain('`my table`');
  });
});

describe('buildDefaultTableQuery', () => {
  it('returns the unsorted template when there is no auto-inc PK', () => {
    expect(buildDefaultTableQuery('users', null)).toBe('SELECT *\nFROM `users`\nLIMIT 100;');
  });

  it('appends ORDER BY <pk> DESC when an auto-inc PK is provided', () => {
    expect(buildDefaultTableQuery('orders', 'id')).toBe(
      'SELECT *\nFROM `orders`\nORDER BY `id` DESC\nLIMIT 100;',
    );
  });

  it('backtick-escapes both the table name and the PK column', () => {
    const sql = buildDefaultTableQuery('my table', 'order id');
    expect(sql).toContain('`my table`');
    expect(sql).toContain('`order id`');
  });
});

describe('buildCreateTableSql', () => {
  const idCol: CreateTableColumn = {
    name: 'id', type: 'INT', nullable: false, default: null, autoIncrement: true, pk: true,
  };
  const nameCol: CreateTableColumn = {
    name: 'name', type: 'VARCHAR(255)', nullable: false, default: null, autoIncrement: false, pk: false,
  };

  it('emits AUTO_INCREMENT and backtick quoting for MySQL', () => {
    const sql = buildCreateTableSql('mysql', null, 'users', [idCol, nameCol]);
    expect(sql).toBe(
      'CREATE TABLE `users` (\n' +
      '  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n' +
      '  `name` VARCHAR(255) NOT NULL\n' +
      ');',
    );
  });

  it('emits IDENTITY clause and double-quote quoting for Postgres', () => {
    const sql = buildCreateTableSql('postgres', null, 'users', [idCol, nameCol]);
    expect(sql).toBe(
      'CREATE TABLE "users" (\n' +
      '  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n' +
      '  "name" VARCHAR(255) NOT NULL\n' +
      ');',
    );
  });

  it('qualifies the table with the schema when one is provided', () => {
    const sql = buildCreateTableSql('mysql', 'shop', 'users', [idCol]);
    expect(sql).toContain('CREATE TABLE `shop`.`users` (');
  });

  it('omits NOT NULL when the column is nullable, no PK, and not auto-inc', () => {
    const col: CreateTableColumn = {
      name: 'note', type: 'TEXT', nullable: true, default: null, autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).not.toContain('NOT NULL');
  });

  it('forces NOT NULL on PK columns even when nullable is set', () => {
    // PK columns are implicitly NOT NULL — keep the DDL valid regardless of UI state.
    const col: CreateTableColumn = {
      name: 'id', type: 'INT', nullable: true, default: null, autoIncrement: false, pk: true,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).toContain('`id` INT NOT NULL PRIMARY KEY');
  });

  it('forces NOT NULL on auto-inc / IDENTITY columns', () => {
    const col: CreateTableColumn = {
      name: 'id', type: 'BIGINT', nullable: true, default: null, autoIncrement: true, pk: false,
    };
    const sql = buildCreateTableSql('postgres', null, 't', [col]);
    expect(sql).toContain('"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY');
  });

  it('passes DEFAULT through verbatim — caller is responsible for quoting', () => {
    const lit: CreateTableColumn = {
      name: 's', type: 'VARCHAR(10)', nullable: true, default: "'hi'", autoIncrement: false, pk: false,
    };
    const fn: CreateTableColumn = {
      name: 'created_at', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP', autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [lit, fn]);
    expect(sql).toContain("`s` VARCHAR(10) DEFAULT 'hi'");
    expect(sql).toContain('`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP');
  });

  it('skips DEFAULT when the value is null or empty', () => {
    const col: CreateTableColumn = {
      name: 'x', type: 'INT', nullable: true, default: '', autoIncrement: false, pk: false,
    };
    const sql = buildCreateTableSql('mysql', null, 't', [col]);
    expect(sql).not.toContain('DEFAULT');
  });

  it('strips embedded quote characters from identifiers to keep DDL safe', () => {
    // No "smart escaping" here — we just remove the offending character so
    // the user can't accidentally close the quoted identifier mid-token.
    const sql = buildCreateTableSql('mysql', null, 'evil`name', [idCol]);
    expect(sql).toContain('CREATE TABLE `evilname` (');
  });
});
