type CellValue = string | number | boolean | null;

export function parseEnumValues(type: string): string[] | null {
  const match = type.match(/^enum\((.+)\)$/i);
  if (!match) return null;
  const values: string[] = [];
  const re = /'((?:[^'\\]|\\.)*)'/g;
  let m;
  while ((m = re.exec(match[1])) !== null) {
    values.push(m[1].replace(/\\'/g, "'").replace(/\\\\/g, '\\'));
  }
  return values.length > 0 ? values : null;
}

export function formatSqlValue(v: CellValue): string {
  if (v === null) return 'NULL';
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  return String(v);
}

export type SqlDialect = 'mysql' | 'postgres';

export interface CreateTableColumn {
  name: string;
  /** Verbatim type token, e.g. "INT", "VARCHAR(255)", "TIMESTAMP". */
  type: string;
  nullable: boolean;
  /** Verbatim default expression — caller is responsible for quoting strings,
   *  passing CURRENT_TIMESTAMP unquoted, etc. Empty/null means no default. */
  default: string | null;
  autoIncrement: boolean;
  pk: boolean;
}

function quoteIdent(d: SqlDialect, s: string): string {
  const ch = d === 'mysql' ? '`' : '"';
  return ch + s.split(ch).join('') + ch;
}

/**
 * Build a CREATE TABLE statement for the given dialect. v1 supports a single
 * inline-PK column, NOT NULL / DEFAULT / AUTO_INCREMENT (or IDENTITY on pg).
 * Composite PKs, secondary indexes, FKs, and CHECK constraints are out of
 * scope; users wanting those can hand-edit the preview.
 */
export function buildCreateTableSql(
  dialect: SqlDialect,
  schema: string | null,
  table: string,
  columns: CreateTableColumn[],
): string {
  const qualified = schema
    ? `${quoteIdent(dialect, schema)}.${quoteIdent(dialect, table)}`
    : quoteIdent(dialect, table);

  const autoInc = dialect === 'mysql' ? 'AUTO_INCREMENT' : 'GENERATED BY DEFAULT AS IDENTITY';

  const lines = columns.map(c => {
    const parts: string[] = [quoteIdent(dialect, c.name), c.type];
    // PK columns are implicitly NOT NULL across both dialects; Postgres IDENTITY
    // additionally requires it. Force the constraint on so the DDL stays valid
    // even if the user ticks PK or auto-inc without un-ticking nullable.
    if (!c.nullable || c.pk || c.autoIncrement) parts.push('NOT NULL');
    if (c.default !== null && c.default !== '') parts.push(`DEFAULT ${c.default}`);
    if (c.autoIncrement) parts.push(autoInc);
    if (c.pk) parts.push('PRIMARY KEY');
    return '  ' + parts.join(' ');
  });

  return `CREATE TABLE ${qualified} (\n${lines.join(',\n')}\n);`;
}

/**
 * Default query template used when the user clicks a table in the sidebar.
 * Sorts by `pkColumn DESC` when provided so the most recent rows appear first
 * — caller passes null for tables without a single auto-incrementing PK,
 * since descending order is meaningless on UUID/string/composite keys.
 */
export function buildDefaultTableQuery(table: string, pkColumn: string | null): string {
  const orderBy = pkColumn ? `\nORDER BY \`${pkColumn}\` DESC` : '';
  return `SELECT *\nFROM \`${table}\`${orderBy}\nLIMIT 100;`;
}

export function buildInsertSql(table: string, values: Record<string, CellValue>): string {
  const cols = Object.keys(values);
  if (cols.length === 0) return `INSERT INTO \`${table}\` () VALUES ();`;
  const colList = cols.map(c => `\`${c}\``).join(', ');
  const valList = cols.map(c => formatSqlValue(values[c]!)).join(', ');
  return `INSERT INTO \`${table}\`\n  (${colList})\nVALUES\n  (${valList});`;
}
